import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header/MainHeader";
import Footer from "../../components/Footer/page";
import { CartProvider } from "./components/CartProvider";
import { Toaster } from "sonner";
import { getNavItems } from "../../lib/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const navData = await getNavItems("mega-menu");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <Header navItems={navData?.menu?.items || []} />
          {children}
          <Toaster position="top-center"
            toastOptions={{
              className: "text-center",
            }} />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
